### ISSUE TITLE
pangeo-forge typical zarr example

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/pangeo-forge-exploration#3]
Lets try to get this dataset into a zarr format using the "standard" pangeo-forge methodology: https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2KW57K4R

> The dataset author, Andy Aschwanden, suggested providing average snapshots of median ice surface elevation at 2100, 2200, 2300 due to the large amount of data.

**Comment by trey-stafford** [comment]
OBE
